name-template: "Priya bot v$RESOLVED_VERSION Released!"
tag-template: "v$RESOLVED_VERSION"
commitish: main
publish: false
prerelease: false
exclude-labels:
  - "No-changelog"
  - "Type: invalid"

category-template: "### $TITLE"
categories:
  - title: "💥 Breaking Changes"
    labels:
      - "Type: breaking"
  - title: "🚀 Features"
    labels:
      - "Type: enhancement"
  - title: "🐛 Bug fixes"
    labels:
      - "Type: bug"
  - title: "📖 Docs"
    labels:
      - "Updates: documentation"
  #- title: "⚙️ Tests"
    #labels:
      #- "Type: tests"
  - title: "🔧 Chores"
    labels:
      - "Updates: dependencies"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "Version: major"
  minor:
    labels:
      - "Version: minor"
  patch:
    labels:
      - "Version: patch"
  default: patch
template: |
  ## Release Notes
  $CHANGES
