name: Format Code
on:
  push:
    paths:
    - "**.py"
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          ref: ${{ github.head_ref }}
      - name: Format using PEP 8
        id: autoyapf
        uses: mritunjaysharma394/autoyapf@v2
        with:
          args: --style pep8 --recursive --in-place .
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "run format"
